name: 'Picky Reviewer Rotation'
description: 'Rotate through a list of reviewers for reviewing a PR'
inputs:
  reviewers:
    description: 'A whitespace separated list of reviewers and/or teams for reviewing'
    required: true
  rotation:
    description: 'The frequency of rotation (e.g. "2 days", "4 weeks", "3 months", "1 year")'
    required: false
    default: '1 week'
  fetch-team-users:
    description: 'Boolean if the rotation list should expand teams to individual members from teams given'
    required: false
  token:
    description: 'A github token to access team members if fetch-team-users is true'
    required: false
outputs:
  reviewer:
    description: 'The assigned reviewer or team'
  team:
    description: 'The team the reviewer belongs to (if applicable)'
  calendar:
    description: 'The immediate review schedule'
runs:
  using: 'node12'
  main: 'index.js'
